import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID, randomBytes, generateKeyPairSync, createHmac, sign } from 'node:crypto';
import { openStore } from '../src/store.mjs';
import { createCollector } from '../src/server.mjs';
import { BUSINESS_ROUTE, PLACE_ROUTE, validateBusinessEvents, STANDARD_PLACES, CATALOG_VERSION } from '../src/places.mjs';
const DAY=86400000, A='synthetic_place_account_A', B='synthetic_place_account_B', now=Date.now();
const dateAt=ms=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ms));
const point=address=>({address,placeId:'',date:dateAt(now),time:'09:00'});
function snap({account=A,from='Fort Lee',to='哥大',day=now-DAY,version=1,status='past',passengers=[]}={}) {
 return {cityKey:'ny_nj',status,departures:[point(from)],destinations:[point(to)],referencePriceCents:1300,currency:'USD',priceKind:'listed_reference',availableSeats:3,passengerCount:passengers.length,creatorOpenid:account,driverOpenid:account,passengerOpenids:passengers,participantEdges:[{openid:account,role:'driver'},...passengers.map(openid=>({openid,role:'passenger'}))],serviceDate:dateAt(day),departureAtMs:day,latestDepartureAtMs:day,tripVersion:version};
}
const business=(extra={})=>({schemaVersion:1,eventId:randomUUID(),tripId:randomUUID(),tripType:'carpool',action:'publish',actorOpenid:A,eventAtMs:now-4*DAY,version:1,before:null,after:snap(),affectedOpenids:[A],synthetic:true,...extra});
const envelope=(...events)=>({schemaVersion:1,events});
const req=(extra={})=>({schemaVersion:1,cityKey:'ny_nj',field:'departure',mode:'driver',...extra});
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'places-')),s=openStore(join(dir,'db.sqlite'),{realEnabled:true});t.after(()=>{s.close();rmSync(dir,{recursive:true,force:true});});return s;}
function enroll(s,openid=A,synthetic=true){const p=s.participate({accountSubject:randomBytes(32).toString('hex'),action:'activate',requestId:randomUUID(),expectedStatusVersion:0,purposeVersion:'ride-research-v1',noticeVersion:'ride-research-notice-2026-09-23',openid,...(synthetic?{synthetic}:{})}).participant;return {...p,sub:p.participantKey,scopes:['batches:write','places:read']};}
function put(s,p,eventName,data,occurredAt=now,eventId=randomUUID()){const b={schemaVersion:1,batchId:randomUUID(),events:[{eventId,eventName,schemaVersion:1,occurredAt,data}]};return s.receive(p,Buffer.from(JSON.stringify(b)),b,now);}
const selected=(extra={})=>({pickerSessionId:randomUUID(),field:'departure',mode:'driver',cityKey:'ny_nj',catalogVersion:'places-v1',rankingVersion:'circle-selection-v1',placeId:'fort_lee',position:0,source:'fixed',...extra});
const seed=s=>s.places.seed({label:'Flushing Library',aliases:['flushing library'],cityKey:'ny_nj',parentRegionId:'flushing',verificationReference:'https://www.queenslibrary.org/about-us/locations/flushing'},now-40*DAY).placeId;

test('server/client standard catalog parity; ambiguous city, island and private labels stay unknown',t=>{const s=fixture(t);try{assert.equal(readFileSync(new URL('../../../utils/placeCatalog.js',import.meta.url),'utf8'),readFileSync(new URL('../src/place-catalog.cjs',import.meta.url),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
 assert.deepEqual(STANDARD_PLACES.map(p=>p.placeId),['fort_lee','columbia','flushing','jfk','ewr','lga','lic','jsq','inwood','midtown','downtown','queens']);
 assert.equal(CATALOG_VERSION,'places-v2');
 assert.equal(s.placeSuggestions(enroll(s),req(),now).catalogVersion,CATALOG_VERSION);
 for(const p of STANDARD_PLACES)for(const label of[p.value,p.label,...p.aliases])assert.equal(s.places.resolve(label,'ny_nj').place_id,p.placeId);
 for(const label of['Newark','纽瓦克','Long Island','Jersey City','Fort Lee apt 2','Downtown Jersey City','Inwood Road','Queens Plaza'])assert.equal(s.places.resolve(label,'ny_nj'),undefined);
});
test('business retries deduplicate and a conflict rolls back the whole batch',t=>{const s=fixture(t),e=business();assert.deepEqual(s.places.ingestBusiness(envelope(e),now).acceptedEventIds,[e.eventId]);assert.deepEqual(s.places.ingestBusiness(envelope(e),now).duplicateEventIds,[e.eventId]);assert.throws(()=>s.places.ingestBusiness(envelope({...e,action:'delete'}),now),{code:'BUSINESS_EVENT_CONFLICT'});assert.throws(()=>s.places.ingestBusiness(envelope(business(),{...e,eventId:randomUUID()}),now),{code:'BUSINESS_VERSION_CONFLICT'});assert.equal(s.db.prepare('SELECT COUNT(*) n FROM place_business_events').get().n,1);assert.throws(()=>validateBusinessEvents(envelope({...e,actorOpenid:''})),{code:'INVALID_BUSINESS_EVENTS'});assert.doesNotThrow(()=>validateBusinessEvents(envelope({...e,actorOpenid:'',action:'status'})));});
test('circle stability, as-of withdrawal, service-city isolation and no airport graph bridging',t=>{const s=fixture(t),first=business({eventAtMs:now-4*DAY,after:snap({day:now-3*DAY})}),back=business({eventAtMs:now-3*DAY,after:snap({from:'哥大',to:'Fort Lee',day:now-2*DAY})});s.places.ingestBusiness(envelope(first,back,business({eventAtMs:now-2*DAY,after:snap({from:'LIC',to:'JFK'})})),now);assert.equal(s.places.circles(A,true,'ny_nj',now-3.5*DAY).circles[0].stable,false);assert.deepEqual(s.places.circles(A,true,'ny_nj',now).circles.map(c=>[c.circleId,c.stable]),[['columbia:fort_lee',true]]);assert.equal(s.places.circles(A,false,'ny_nj',now).circles.length,0);assert.equal(s.places.circles(A,true,'boston',now).circles.length,0);s.places.ingestBusiness(envelope({...back,eventId:randomUUID(),version:2,action:'delete',eventAtMs:now-DAY,before:back.after,after:null}),now);assert.equal(s.places.circles(A,true,'ny_nj',now).circles[0].stable,false);assert.equal(s.places.circles(A,true,'ny_nj',now-1.5*DAY).circles[0].stable,true);});
test('one publish enables verified POI, unknown/private text stays quarantined and synthetic usage never enters real suggestions',t=>{const s=fixture(t),p=enroll(s),real=enroll(s,B,false),poi=seed(s);assert.equal(s.placeSuggestions(p,req(),now).places.length,0);s.places.ingestBusiness(envelope(business({after:snap({from:'Flushing Library'})}),business({after:snap({from:'Home apt 9 phone 201-555-1212'})}),business({after:snap({from:'Unknown public park'})})),now);const r=s.placeSuggestions(p,req({counterpartPlaceId:'flushing'}),now);assert.equal(r.places[0].placeId,poi);assert.equal(r.rankingBasis,'historical_usage');assert.equal(r.places[0].selectionCount30d,0);for(const secret of[A,B,'apt 9','201-555','Unknown public park'])assert.equal(JSON.stringify(r).includes(secret),false);assert.equal(s.placeSuggestions(real,req(),now).places.length,0);assert.equal(s.places.pending({limit:10}).candidates[0].label,'Unknown public park');const bad=s.db.prepare("SELECT candidate_id FROM place_candidates WHERE classification='private'").get();assert.throws(()=>s.places.approve({candidateId:bad.candidate_id,label:'Home',parentRegionId:'fort_lee',verification:'manual_public_poi',verificationReference:'https://example.com'},now),{code:'PLACE_NOT_PUBLIC'});});
test('documented public approval promotes original publication into reserved new slot',t=>{const s=fixture(t),p=enroll(s);s.places.ingestBusiness(envelope(business({after:snap({from:'Example Public Museum'})})),now);const c=s.places.pending({limit:10}).candidates[0];assert.equal(s.placeSuggestions(p,req(),now).places.length,0);const a=s.places.approve({candidateId:c.candidateId,label:'Example Public Museum',parentRegionId:'unknown',verification:'manual_public_poi',verificationReference:'https://example.org/museum'},now);const r=s.placeSuggestions(p,req(),now+300001);assert.equal(r.places[0].placeId,a.placeId);assert.equal(r.places[0].source,'new');assert.equal(r.circles.length,0);});
test('selection retries and daily person/place/side cap are distinct from raw research events',t=>{const s=fixture(t),p=enroll(s),poi=seed(s);s.places.ingestBusiness(envelope(business({after:snap({from:'Flushing Library'})})),now);const d=selected({placeId:poi,source:'city'}),id=randomUUID();put(s,p,'place_picker_selected',d,now,id);put(s,p,'place_picker_selected',d,now,id);put(s,p,'place_picker_selected',{...d,pickerSessionId:randomUUID()},now);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM place_selection_votes').get().n,1);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM eligible_events').get().n,2);put(s,p,'place_picker_selected',{...d,field:'destination'},now);put(s,p,'place_picker_selected',d,now-DAY);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM place_selection_votes').get().n,3);const r=s.placeSuggestions(p,req(),now);assert.equal(r.rankingBasis,'confirmed_selection');assert.equal(r.places[0].selectionCount30d,2);assert.equal(r.places[0].uniqueUsers30d,1);put(s,p,'place_picker_selected',{...d,placeId:'custom'},now);assert.equal(s.db.prepare('SELECT COUNT(*) n FROM place_selection_votes').get().n,3);});
test('vote-before-outbox and reverse outbox order reconcile as-of circles without future-information leakage',t=>{const s=fixture(t),p=enroll(s),poi=seed(s),old=business({eventAtMs:now-4*DAY,after:snap({day:now-3*DAY})}),late=business({eventAtMs:now-3*DAY,after:snap({from:'哥大',to:'Fort Lee',day:now-2*DAY})}),custom=business({eventAtMs:now-DAY,after:snap({from:'Flushing Library',to:'JFK'})});put(s,p,'place_picker_selected',selected({placeId:poi,source:'city'}),now-0.5*DAY);s.places.ingestBusiness(envelope(custom,late,old),now);assert.deepEqual(JSON.parse(s.db.prepare('SELECT circle_ids FROM place_selection_votes').get().circle_ids),['columbia:fort_lee']);assert.deepEqual(JSON.parse(s.db.prepare('SELECT circle_ids FROM place_public_usage WHERE event_id=?').get(custom.eventId).circle_ids),['columbia:fort_lee']);const before=s.db.prepare('SELECT circle_ids FROM place_selection_votes').get().circle_ids;put(s,p,'followup_answer',{followupId:randomUUID(),tripKey:old.tripId,tripType:'carpool',role:'driver',outcome:'no',outcomeScope:'driver_any_passenger'},now-0.25*DAY);assert.equal(s.db.prepare('SELECT circle_ids FROM place_selection_votes').get().circle_ids,before);assert.equal(s.places.circles(A,true,'ny_nj',now).circles.find(c=>c.circleId==='columbia:fort_lee').stable,false);});
test('legacy version zero cannot override transactional delete; snapshots immutable and scope/account strict',t=>{const s=fixture(t),p=enroll(s),e=business(),removed={...e,eventId:randomUUID(),version:2,action:'delete',eventAtMs:now-DAY,before:e.after,after:null},legacy={...e,eventId:randomUUID(),version:0,action:'legacy_snapshot',source:'legacy_snapshot',eventAtMs:now-5*DAY,after:{...e.after,tripVersion:0}};s.places.ingestBusiness(envelope(removed,legacy,e),now);assert.equal(s.places.circles(A,true,'ny_nj',now).circles.length,0);assert.equal(s.places.circles(A,true,'ny_nj',now-4.5*DAY).circles[0].evidenceKind,'legacy_snapshot');const a=s.placeSuggestions(p,req(),now),b=s.placeSuggestions(p,req(),now+1000),c=s.placeSuggestions(p,req(),now+300001);assert.equal(a.snapshotId,b.snapshotId);assert.notEqual(a.snapshotId,c.snapshotId);assert.deepEqual(JSON.parse(s.db.prepare('SELECT response FROM place_rank_snapshots WHERE snapshot_id=?').get(a.snapshotId).response),a);assert.throws(()=>s.placeSuggestions({...p,scopes:undefined},req(),now),{code:'PLACE_SCOPE_REQUIRED'});assert.throws(()=>s.placeSuggestions(p,{...req(),openid:B},now),{code:'INVALID_PLACE_REQUEST'});});
test('followup denominator matches past/close roles and preserves deleted facts; synthetic retention bounded',t=>{const s=fixture(t),e=business({after:snap({passengers:[B],day:now-2*DAY})});s.places.ingestBusiness(envelope(e,business({after:snap({status:'open',day:now-2*DAY})})),now);assert.equal(s.places.status(now).followupPopulation[0].currentlyEligible,2);s.places.ingestBusiness(envelope({...e,eventId:randomUUID(),version:2,action:'delete',before:e.after,after:null,eventAtMs:now-DAY}),now);assert.equal(s.places.status(now).followupPopulation[0].currentlyEligible,0);assert.equal(s.places.status(now).business[0].count,3);assert.equal(s.prune(now+15*DAY).places.place_business_events,3);});
test('HTTP routes enforce signed business origin, replay, token scope and revocation',async t=>{const dir=mkdtempSync(join(tmpdir(),'places-http-')),keys=generateKeyPairSync('ed25519'),config={dbPath:join(dir,'db.sqlite'),host:'127.0.0.1',port:0,minFreeBytes:0,adminSocket:join(dir,'run/admin.sock'),adminToken:randomBytes(32).toString('base64url'),privatePem:keys.privateKey.export({type:'pkcs8',format:'pem'}),bridgeKey:randomBytes(32),realEnabled:true,purposeVersion:'ride-research-v1'},app=createCollector(config),address=await app.start();t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});const post=async(route,body,headers={})=>{const r=await fetch(`http://127.0.0.1:${address.port}${route}`,{method:'POST',body:JSON.stringify(body),headers:{'Content-Type':'application/json',...headers}});return{status:r.status,body:await r.json()};};const p=enroll(app.store),token=app.tokens.issue(p).token;assert.equal((await post(PLACE_ROUTE,req(),{Authorization:`Bearer ${token}`})).status,200);const[header,payload]=token.split('.'),claims=JSON.parse(Buffer.from(payload,'base64url').toString());delete claims.scopes;const input=`${header}.${Buffer.from(JSON.stringify(claims)).toString('base64url')}`,old=`${input}.${sign(null,Buffer.from(input),keys.privateKey).toString('base64url')}`;assert.equal((await post(PLACE_ROUTE,req(),{Authorization:`Bearer ${old}`})).body.error,'PLACE_SCOPE_REQUIRED');const b=envelope(business());assert.equal((await post(BUSINESS_ROUTE,b)).status,401);const timestamp=String(Date.now()),nonce=randomBytes(16).toString('hex'),signature=createHmac('sha256',config.bridgeKey).update(`${timestamp}\n${nonce}\n${JSON.stringify(b)}`).digest('hex'),h={'x-linkx-timestamp':timestamp,'x-linkx-nonce':nonce,'x-linkx-signature':signature};assert.equal((await post(BUSINESS_ROUTE,b,h)).status,200);assert.equal((await post(BUSINESS_ROUTE,b,h)).body.error,'BRIDGE_REPLAY');app.store.applyState({participantKey:p.participantKey,grantId:p.grantId,status:'revoked',statusVersion:p.statusVersion+1,purposeVersion:p.purposeVersion,synthetic:p.synthetic});assert.equal((await post(PLACE_ROUTE,req(),{Authorization:`Bearer ${token}`})).status,403);});
test('legacy usage uses planned service date while circle evidence retains snapshot observation time',t=>{const s=fixture(t),poi=seed(s),past=business({version:0,action:'legacy_snapshot',source:'legacy_snapshot',eventAtMs:now-1000,after:snap({from:'Flushing Library',version:0,day:now-40*DAY})});s.places.ingestBusiness(envelope(past),now);const row=s.db.prepare('SELECT occurred_at,evidence_at FROM place_public_usage WHERE place_id=?').get(poi);assert.equal(dateAt(row.occurred_at),dateAt(now-40*DAY));assert.equal(row.evidence_at,now-1000);});
