// Generated by services/backend/scripts/sync-cloud-queries.mjs.
'use strict'
const fs = require('node:fs')
const path = require('node:path')
const { getIdentity } = require('./context')
const { createQueryHandler } = require('./query-bridge')
function getKey() {
  const value = fs.readFileSync(path.join(__dirname, 'query-bridge.secret'), 'utf8').trim()
  if (!/^[a-f0-9]{64}$/.test(value)) throw Error('QUERY_UNAVAILABLE')
  return Buffer.from(value, 'hex')
}
exports.main = createQueryHandler({ action: "rides.history", fields: [], getIdentity, getKey })
